//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SerialData
{
    using System;
    using System.Collections.Generic;
    
    public partial class EuiList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EuiList()
        {
            this.SerialNumbers = new HashSet<SerialNumber>();
        }
    
        public int Id { get; set; }
        public string EUI { get; set; }
        public int ProductionSiteId { get; set; }
        public string VendorEui { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SerialNumber> SerialNumbers { get; set; }
    }
}
